WestwindSolution/WestwindWebApp/Pages/Products/Query.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

#region namespaces for BLL and Entities
using WestwindSystem.BLL;
using WestwindSystem.Entities;
#endregion

namespace WestwindWebApp.Pages.Products
{
    public class QueryModel : PageModel
    {
        #region Setup constructor DI for BLL
        private readonly CategoryServices _categoryServices;
        private readonly ProductServices _productServices;

        public QueryModel(CategoryServices categoryServices, ProductServices productServices)
        {
            _categoryServices = categoryServices;
            _productServices = productServices;

            // Fetch from the system (CategoryServices) a list of Category
            CategoryList = _categoryServices.List();
            CategorySelectionList = new SelectList(_categoryServices.List(), "Id", "CategoryName");

        }
        #endregion

        #region Properties to populate Category select element and track is selected value
        public List<Category> CategoryList { get; private set; }
        [BindProperty()]
        public int SelectedCategoryId { get; set; }

        public SelectList CategorySelectionList { get; private set; }
        #endregion

        [BindProperty]
        public string? QueryProductName { get; set; }

        [TempData]
        public string? FeedbackMessage { get; set; }

        public List<Product>? QueryResultList { get; private set; }

        public void OnGet()
        {            

        }

        public void OnPostSearchByCategory()
        {
            FeedbackMessage = "You click on Search By Category";
            QueryResultList = _productServices.FindProductsByCategoryId(SelectedCategoryId);
            //return RedirectToPage(new { currentSelectedCategoryId = SelectedCategoryId });
        }

        public void OnPostSearchByProductName()
        {
            FeedbackMessage = "You click on Search By Product Name";
            QueryResultList = _productServices.FindProductsByProductName(QueryProductName);

            //return RedirectToPage();
        }

        public IActionResult OnPostClearForm()
        {
            FeedbackMessage = "You click on Clear button";
            //SelectedCategoryId = 0;
            //QueryProductName = null;
            return RedirectToPage();
        }
    }
}

WestwindSolution/WestwindWebApp/Pages/Territories/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WestwindSystem.Entities;
using WestwindSystem.BLL;
using System.Runtime.CompilerServices;
using WestwindWebApp.Helpers;

namespace WestwindWebApp.Pages.Territories
{
    public class IndexModel : PageModel
    {
        private readonly TerritoryServices _territoryServices;

        public IndexModel(TerritoryServices territoryServices)
        {
            _territoryServices = territoryServices;
        }

        public List<Territory>? QueryResultList { get; private set; }


        public string InfoMessage { get; set; }
        public string ErrorMessage { get; set; }

        #region Paginator
        //my desired page size
        private const int PAGE_SIZE = 10;
        //be able to hold an instance of the Paginator
        public Paginator Pager { get; set; }
        #endregion


        public void OnGet(int? currentPage)
        {
            try
            {
                //determine the current page number
                int pagenumber = currentPage.HasValue ? currentPage.Value : 1;
                //setup the current state of the paginator (sizing)
                PageState current = new(pagenumber, PAGE_SIZE);
                //temporary local integer to hold the results of the query's total collection size
                //  this will be need by the Paginator during the paginator's execution
                int totalcount;

                //we need to pass paging data into our query so that efficiencies in the
                //  system will ONLY return the amount of records to actually be display
                //  on the browser page.

                //QueryResultList = _territoryServices.List(); --what we had before
                QueryResultList = _territoryServices.List(pagenumber, PAGE_SIZE, out totalcount);

                //create the needed Pagnator instance
                Pager = new Paginator(totalcount, current);

                

                InfoMessage = $"Query returned {QueryResultList.Count} results";
            }
            catch
            {
                ErrorMessage = "Error Reading Territories";
            }
            
        }
    }
}

WestwindSolution/WestwindWebApp/Pages/Territories/Query.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using WestwindSystem.Entities;
using WestwindSystem.BLL;

namespace WestwindWebApp.Pages.Territories
{
    public class QueryModel : PageModel
    {
        private readonly RegionServices _regionServices;
        private readonly TerritoryServices _territoryServices;

        public QueryModel(RegionServices regionServices, TerritoryServices territoryServices)
        {
            _regionServices = regionServices;
            _territoryServices = territoryServices;

            Regions = _regionServices.GetAll();
        }

        public List<Region> Regions { get; private set; }

        [BindProperty]
        public int? SelectedRegionId { get; set; }

        public List<Territory> QueryResultList { get; private set; }
        
        public string? FeedbackMessage { get; set; }

        [BindProperty]
        public string TerritoryQuery { get; set; }

        public void OnGet()
        {
        }

        public void OnPostFilterByTerritory()
        {
            if (TerritoryQuery != null)
            {
                QueryResultList = _territoryServices.FindByPartialName(TerritoryQuery);
            }
            else
            {
                FeedbackMessage = "You need to enter a territory first.";
            }
        }

        public void OnPostFilterByRegion()
        {
            // Check if a valid region was selected
            if (SelectedRegionId.HasValue)
            {
                QueryResultList = _territoryServices.FindByRegionId(SelectedRegionId.Value);
            }
            else
            {
                FeedbackMessage = "You must select a region first.";
            }
        }
    }
}

WestwindSolution/WestwindWebApp/Pages/Territories/Index.cshtml
@page
@model WestwindWebApp.Pages.Territories.IndexModel
@{
}

<h1>Territories</h1>

@if (Model.InfoMessage != null)
{

}
@if (Model.ErrorMessage != null)
{

}
@if(Model.QueryResultList != null && Model.QueryResultList.Count > 0)
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Description</th>
                <th>Region</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var currentTerritory in Model.QueryResultList)
            {
                <tr>
                    <td>@currentTerritory.TerritoryId</td>
                    <td>@currentTerritory.TerritoryDescription</td>
                    <td>@currentTerritory.Region.RegionDescription</td>
                </tr>
            }
        </tbody>
        <tfoot>

            @*used for summay table information eg totals
        used for displaying paging information
        *@
            <tr>
                <td colspan="3">
                    @{
                        //the pageRef is the string representation of the
                        //  the value to be displayed AND it's numeric
                        //the string maybe be a character line : Next
                        //the string maybe be a numeric : 4
                        //  First Previous 1 2 3 4 5 Next Last
                        foreach (var pageRef in Model.Pager)
                        {
                            if (pageRef == Model.Pager.CurrentPage)
                            {
                                <b>@pageRef.Text</b>
                            }
                            else
                            {
                                //create an anchor tag to move to
                                //  the desired collection page
                                //the target of the anchor destination
                                //  is your current web cshtml
                                //this will cause a OnGet issue
                                // .Page is the numeric representation
                                //      of the desired page
                                //for the asp-page your page name reference
                                //  MUST be based from the folder name Pages
                                <a title="Page @pageRef.Page"
                                    asp-page="/Territories/Index"
                                    asp-route-currentpage="@pageRef.Page">
                                    @pageRef.Text
                                </a>
                            }
                        }
                    }
                </td>
            </tr>
        </tfoot>
    </table>
}

WestwindSolution/WestwindWebApp/Pages/Territories/Query.cshtml
@page
@model WestwindWebApp.Pages.Territories.QueryModel
@{
}
<h1>Territory Queries</h1>

@if(Model.FeedbackMessage != null)
{
    <div class="alert alert-warning">
        @Model.FeedbackMessage
    </div>
}

<form method="post">
    <div>
        <label asp-for="SelectedRegionId">Select region:</label>
        <select asp-for="SelectedRegionId"
            class="form-select" >
            <option selected>Open this select menu</option>
            @foreach(var currentRegion in Model.Regions)
            {
                <option value="@currentRegion.RegionId">@currentRegion.RegionDescription</option>
            }
        </select>
    </div>
    <div>
        <label asp-for="TerritoryQuery">Name:</label>
        <input asp-for="TerritoryQuery" class="form-control"/>
    </div>
    <div>
        <button type="submit"
                asp-page-handler="FilterByRegion"
            class="btn btn-primary">Search by Region</button>
        <button type="submit"
                asp-page-handler="FilterByTerritory"
                class="btn btn-primary">
            Search by Name
        </button>
    </div>
</form>

@if(Model.QueryResultList != null && Model.QueryResultList.Count > 0) 
{
    <table>
        <thead>
            <tr>
                <th style="width: 200px">ID</th>
                <th>Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var currentTerritory in Model.QueryResultList)
            {
                <tr>
                    <td>@currentTerritory.TerritoryId</td>
                    <td>@currentTerritory.TerritoryDescription</td>
                </tr>
            }
        </tbody>
    </table>
}