WestwindSolution/WestwindWebApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WestwindWebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WestwindSolution/WestwindWebApp/Pages/FormControlDemoUsingPureHTML.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WestwindWebApp.Pages
{
    public class FormControlDemoUsingPureHtmlModel : PageModel
    {
        [TempData]
        public string FeedbackMessage { get; set; } = string.Empty;

        [BindProperty]
        public string Username { get; set; } = string.Empty;

        [BindProperty]
        public int Age { get; set; }

        public void OnGet()
        {
        }

        public void OnPost()
        {
            FeedbackMessage = $"Username = {Username}, Age = {Age}";
        }
    }
}

WestwindSolution/WestwindWebApp/Pages/FormControlDemoUsingTagHelpers.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WestwindWebApp.Pages
{
    public class FormControlDemoUsingTagHelpersModel : PageModel
    {
        [TempData]
        public string FeedbackMessage { get; set; } = string.Empty;

        [BindProperty]
        public string Username { get; set; } = string.Empty;

        [BindProperty]
        public int Age { get; set; }

        [BindProperty]
        public string Gender { get; set; } = string.Empty;

        [BindProperty]
        public string Department { get; set; } = string.Empty;

        [BindProperty] 
        public string Comments { get; set; } = string.Empty;

        [BindProperty]
        public bool Subscribe { get; set; }

        public string[] GenderOptions { get; } = {"Male", "Female", "Unspecified" };

        public SelectListItem[] DepartmentListItems =  
        { 
            new SelectListItem { Value = "DMIT", Text = "Digital Media and IT"},
            new SelectListItem { Value = "BAIST", Text = "Bachelor of Applied Information Systems Technolog"},
            new SelectListItem { Value = "CNT", Text = "Computer Network Technology"},
            new SelectListItem { Value = "CET", Text = "Computer Engineering Technology"},

        };

        public void OnGet()
        {
        }

        public void OnPost()
        {
            FeedbackMessage = $"Username = {Username}, Age = {Age}, Gender = {Gender}, Department = {Department}, Comments = {Comments}, Subscribe = {Subscribe}";
        }
    }
}

WestwindSolution/WestwindWebApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

#region custom namepsaces
using WestwindSystem.BLL;
using WestwindSystem.Entities;
#endregion 

namespace WestwindWebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        private readonly BuildVersionServices _buildVersionServices;

        public IndexModel(ILogger<IndexModel> logger, BuildVersionServices buildVersionServices)
        {
            _logger = logger;
            _buildVersionServices = buildVersionServices;
        }

        public BuildVersion CurrentBuildVersion { get; set; } = null!;

        public void OnGet()
        {
            CurrentBuildVersion = _buildVersionServices.GetBuildVersion();
        }
    }
}

WestwindSolution/WestwindWebApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WestwindWebApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

WestwindSolution/WestwindWebApp/Pages/SendMail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net;
using System.Net.Mail;  // for WebMail class

namespace WestwindWebApp.Pages
{
    public class SendMailModel : PageModel
    {
        public void OnGet()
        {
            //var gmailUsername = Configuration["GmailCredentials:Username"];
            //var gmailAppPassword = Configuration["GmailCredentials:Password"];
            //FeedbackMessage = $"Gmail username = {gmailUsername} <br />";
            //FeedbackMessage += $"Gmail app password = {gmailAppPassword} <br />";
        }

        private readonly IConfiguration Configuration;

        public SendMailModel(IConfiguration configuration)
        {
            this.Configuration = configuration;
        }

        [BindProperty]
        public string FeedbackMessage { get; set; } = string.Empty;

        [BindProperty]
        public string MailUsername { get; set; } = string.Empty;

        [BindProperty]
        public string MailAppPassword { get; set; } = string.Empty;

        [BindProperty]
        public string MailToAddress { get; set; } = string.Empty;

        [BindProperty]
        public string MailSubject { get; set; } = string.Empty;

        [BindProperty]
        public string MailMessage { get; set; } = string.Empty;

        public void OnPostSendMail()
        {
            //FeedbackMessage = "<h2>Send Mail button clicked</h2>";
            var sendMailClient = new SmtpClient();
            sendMailClient.Host = "smtp.gmail.com";
            sendMailClient.Port = 587;
            sendMailClient.EnableSsl = true;

            var sendMailCredentials = new NetworkCredential();
            MailUsername = Configuration["GmailCredentials:Username"];
            MailAppPassword = Configuration["GmailCredentials:Password"];
            sendMailCredentials.UserName = MailUsername;
            sendMailCredentials.Password = MailAppPassword;

            sendMailClient.Credentials = sendMailCredentials;

            var sendFromAddress = new MailAddress(MailUsername);
            var sendToAddress = new MailAddress(MailToAddress);

            var mailMessage = new MailMessage(sendFromAddress, sendToAddress);
            mailMessage.Subject = MailSubject;
            mailMessage.Body = MailMessage;

            try
            {
                sendMailClient.Send(mailMessage);
                // Clear the form fields associated with the properties below
                MailToAddress = "";
                MailSubject = "";
                MailMessage = "";
                FeedbackMessage = "<div class='alert alert-primary'>Email Sent!</div>";
            }
            catch (Exception ex)
            {
                FeedbackMessage = $"<div class='alert alert-danger'>Error sending email {ex.Message}</div>";
            }
        }

        public void OnPostClearForm()
        {
            FeedbackMessage = "<h2>Clear Form button clicked</h2>";
        }

   
    }
}

WestwindSolution/WestwindWebApp/Pages/FormControlDemoUsingPureHTML.cshtml
@page
@model WestwindWebApp.Pages.FormControlDemoUsingPureHtmlModel
@{
}
<div class="alert-info">
    @Model.FeedbackMessage
</div>
<form method="post">

    <div class="mb-3">
        <label for="Username" class="form-label">Username</label>
        <input class="form-control"
               type="text"
               id="Username"
               name="Username"
               value="@Model.Username"/>
    </div>
    <div class="mb-3">
        <label for="Age" class="form-label">Age</label>
        <input type="number" 
               min="18" max="65"
               class="form-control"
               id="Age"
               name="Age"
               value="@Model.Age"/>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>

</form>

WestwindSolution/WestwindWebApp/Pages/FormControlDemoUsingTagHelpers.cshtml
@page
@model WestwindWebApp.Pages.FormControlDemoUsingTagHelpersModel
@{
}
<div class="alert-info">
    @Model.FeedbackMessage
</div>
<form method="post">

    <div class="mb-3">
        <label asp-for="Username" class="form-label">Username</label>
        <input asp-for="Username"
               class="form-control"
               placeholder="Enter your name"
                 />
    </div>
    <div class="mb-3">
        <label asp-for="Age" class="form-label">Age</label>
        <input asp-for="Age" 
               min="18" max="99"
               class="form-control"                              
               />
    </div>

    <div class="btn-group" role="group">
        Gender:
        
        @*<div class="form-check">
            <input class="form-check-input" type="radio" 
                asp-for="Gender" value="Male">
            <label class="form-check-label" asp-for="Gender">
                Male
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" 
                asp-for="Gender" value="Female" checked>
            <label class="form-check-label" asp-for="Gender">
                Female
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio"
                   asp-for="Gender" value="Unspecified">
            <label class="form-check-label" asp-for="Gender">
                Unspecified
            </label>
        </div>*@

        @foreach (var currentGender in Model.GenderOptions)
        {
            <div class="form-check">
                <input class="form-check-input" type="radio"
                   asp-for="Gender"
                   id="Gender@(currentGender)"
                   value="@currentGender">
                <label class="form-check-label" asp-for="Gender">
                    @currentGender
                </label>
            </div>
        }
    </div>

    <label asp-for="Department">Department</label>
   @* <select asp-for="Department"
        class="form-select" aria-label="Department">
        <option selected >Open this select menu</option>
        <option value="DMIT">Digital Media and IT</option>
        <option value="BAIST">Bachelor of Applied Information Systems Technology</option>
        <option value="CNT">Computer Network Technology</option>
        <option value="CET">Computer Engineering Technology</option>
    </select>*@
    <select asp-for="Department"
            class="form-select" 
            asp-items="Model.DepartmentListItems"
            aria-label="Department">
        <option selected>Open this select menu</option>        
    </select>

    <div class="mb-3">
        <label asp-for="Comments">Comments</label>
        <textarea asp-for="Comments" cols="50" rows="5" class="form-control">
        </textarea>
    </div>

    <div class="form-check">
        <input class="form-check-input" 
            asp-for="Subscribe" >
        <label class="form-check-label" asp-for="Subscribe">
            Subcribe to promotions
        </label>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>

</form>

WestwindSolution/WestwindWebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to the Westwind Demo application</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

@if (Model.CurrentBuildVersion == null)
{
    <div class="alert alert-warning" role="alert">
        Build Version Unknown
    </div>
}
else
{
    <div class="alert alert-info" role="alert">
        Database Version: @Model.CurrentBuildVersion.Major . @Model.CurrentBuildVersion.Minor . @Model.CurrentBuildVersion.Build
        &nbsp;
        released on @Model.CurrentBuildVersion.ReleaseDate.ToString("MMM dd, yyyy")
    </div>
}

WestwindSolution/WestwindWebApp/Pages/SendMail.cshtml
@page
@model WestwindWebApp.Pages.SendMailModel
@{
}
<h1>Email Client App</h1>

@Html.Raw(Model.FeedbackMessage)

<form method="post">
   @* <div class="mb-3">
        <label asp-for="MailUsername"
               class="form-label" >
               Gmail Email address
        </label>
        <input asp-for="MailUsername" 
            type="email" 
            class="form-control"  
            required
            >
    </div>
    <div class="mb-3">
        <label asp-for="MailAppPassword" 
                class="form-label">
                Gmail App Password
        </label>
        <input asp-for="MailAppPassword" 
            type="password" 
            required
            class="form-control">
    </div>*@
    <div class="mb-3">
        <label asp-for="MailToAddress"
               class="form-label">
            Mail To Email address
        </label>
        <input asp-for="MailToAddress"
               type="email"
               class="form-control"
               required>
    </div>
    <div class="mb-3">
        <label asp-for="MailSubject"
               class="form-label">
           Subject
        </label>
        <input asp-for="MailSubject"
               class="form-control"
               required>
    </div>
    <div class="mb-3">
        <label asp-for="MailMessage"
               class="form-label">
            Message
        </label>
        <textarea asp-for="MailMessage"
            rows="10"
            cols="50"
            class="form-control"
            required>
        </textarea>
    </div>
    <button type="submit" 
        asp-page-handler="SendMail"
        class="btn btn-primary">
        Send Mail
    </button>
    <button type="submit" 
        asp-page-handler="ClearForm"
        class="btn btn-secondary">
        Clear
    </button>
</form>