WestwindSolution/WestwindWebApp/Pages/Products/ProductCategory.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

#region namespaces for BLL and Entities
using WestwindSystem.BLL;
using WestwindSystem.Entities;
#endregion

namespace WestwindWebApp.Pages.Products
{
    public class ProductCategoryModel : PageModel
    {
        #region internal fields
        private readonly CategoryServices _categoryServices;
        private readonly ProductServices _productServices;
        private readonly SupplierServices _supplierServices;
        #endregion

        #region data properties for page

        // Data source for category select element
        public SelectList CategorySelectList { get; private set; }
        // Bindable property for value selected from select element
        [BindProperty]
        public int? SelectedCategoryId { get; set; }

        public SelectList SupplierSelectList { get; private set; }

        // Query result property
        public List<Product>? QueryProductResultList { get; private set; }

        // Feedback message properties
        public string? InfoMessage { get; set; }
        public string? ErrorMessage { get; set; }

        #endregion

        #region constructor with dependencies
        public ProductCategoryModel(
            CategoryServices categoryServices, 
            ProductServices productServices,
            SupplierServices supplierServices)
        {
            _categoryServices = categoryServices;
            _productServices = productServices;
            _supplierServices = supplierServices;

            // Fetch list of categories
            List<Category> categories = _categoryServices.List();
            CategorySelectList = new SelectList(categories, "Id", "CategoryName");

            // Fetch list of suppliers
            List<Supplier> suppliers = _supplierServices.List();
            SupplierSelectList = new SelectList(suppliers, "SupplierId", "ListItemText");
        }

        #endregion

        #region page handlers
        public void OnGet()
        {
        }
        public IActionResult OnPostFetchProducts()
        {
            IActionResult nextPage = Page();

            // Verify that a valid category was selected
            if (SelectedCategoryId.HasValue && SelectedCategoryId.Value > 0)
            {
                int categoryId = SelectedCategoryId.Value;
                QueryProductResultList = _productServices.FindProductsByCategoryId(categoryId);
                InfoMessage = $"Query returned {QueryProductResultList.Count} record(s).";
            }
            else
            {
                ErrorMessage = "A valid category must be selected";
            }

            return nextPage;
        }
        public IActionResult OnPostClear()
        {
            IActionResult nextPage = Page();
            SelectedCategoryId = null;
            QueryProductResultList = null;
            ModelState.Clear();

            return nextPage;
        }
        public IActionResult OnPostNewProduct()
        {
            IActionResult nextPage = RedirectToPage("/Products/ProductCrud");

            return nextPage;
        }


        #endregion

    }
}

WestwindSolution/WestwindWebApp/Pages/Products/ProductCrud.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

#region namespaces for BLL and Entities
using WestwindSystem.BLL;
using WestwindSystem.Entities;
#endregion

namespace WestwindWebApp.Pages.Products
{
    public class ProductCrudModel : PageModel
    {
        #region internal fields
        private readonly CategoryServices _categoryServices;
        private readonly ProductServices _productServices;
        private readonly SupplierServices _supplierServices;

        #endregion

        #region data properties for page
        [BindProperty(SupportsGet = true)]
        public int? EditProductId { get; set; }

        // Data source for category select element
        public SelectList CategorySelectList { get; private set; }
        // Bindable property for value selected from select element
        [BindProperty]
        public int? SelectedCategoryId { get; set; }

        public SelectList SupplierSelectList { get; private set; }
        [BindProperty]
        public int? SelectedSupplierId { get; set; }

        // The CurrentProduct to add, update, or delete.
        [BindProperty]
        public Product CurrentProduct { get; set; }

        public string InfoMessage { get; set; }
        public string ErrorMessage { get; set; }

        #endregion

        #region constructor with depdendencies
        public ProductCrudModel(
            CategoryServices categoryServices,
            ProductServices productServices,
            SupplierServices supplierServices)
        {
            _categoryServices = categoryServices;
            _supplierServices = supplierServices;
            _productServices = productServices;

            // Fetch list of categories
            List<Category> categories = _categoryServices.List();
            CategorySelectList = new SelectList(categories, "Id", "CategoryName");

            // Fetch list of suppliers
            List<Supplier> suppliers = _supplierServices.List();
            SupplierSelectList = new SelectList(suppliers, "SupplierId", "ListItemText");

        }

        #endregion

        #region page handlers
        public void OnGet()
        {
            if (EditProductId != null)
            {
                int productId = EditProductId.Value;
                var querySingleResult = _productServices.GetById(productId);
                if (querySingleResult != null)
                {
                    CurrentProduct = querySingleResult;
                }
                else
                {
                    ErrorMessage = $"Invalid product id of {EditProductId}";
                }
            }
        }

        #endregion
    }
}

WestwindSolution/WestwindWebApp/Pages/Products/Query.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

#region namespaces for BLL and Entities
using WestwindSystem.BLL;
using WestwindSystem.Entities;
#endregion

namespace WestwindWebApp.Pages.Products
{
    public class QueryModel : PageModel
    {
        #region Setup constructor DI for BLL
        private readonly CategoryServices _categoryServices;
        private readonly ProductServices _productServices;

        public QueryModel(CategoryServices categoryServices, ProductServices productServices)
        {
            _categoryServices = categoryServices;
            _productServices = productServices;

            // Fetch from the system (CategoryServices) a list of Category
            CategoryList = _categoryServices.List();
            CategorySelectionList = new SelectList(_categoryServices.List(), "Id", "CategoryName");

        }
        #endregion

        #region Properties to populate Category select element and track is selected value
        public List<Category> CategoryList { get; private set; }
        [BindProperty()]
        public int SelectedCategoryId { get; set; }

        public SelectList CategorySelectionList { get; private set; }
        #endregion

        [BindProperty]
        public string? QueryProductName { get; set; }

        [TempData]
        public string? FeedbackMessage { get; set; }

        public List<Product>? QueryResultList { get; private set; }

        public void OnGet()
        {            

        }

        public void OnPostSearchByCategory()
        {
            FeedbackMessage = "You click on Search By Category";
            QueryResultList = _productServices.FindProductsByCategoryId(SelectedCategoryId);
            //return RedirectToPage(new { currentSelectedCategoryId = SelectedCategoryId });
        }

        public void OnPostSearchByProductName()
        {
            FeedbackMessage = "You click on Search By Product Name";
            QueryResultList = _productServices.FindProductsByProductName(QueryProductName);

            //return RedirectToPage();
        }

        public IActionResult OnPostClearForm()
        {
            FeedbackMessage = "You click on Clear button";
            //SelectedCategoryId = 0;
            //QueryProductName = null;
            return RedirectToPage();
        }
    }
}

WestwindSolution/WestwindWebApp/Pages/Territories/Query.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using WestwindSystem.Entities;
using WestwindSystem.BLL;

namespace WestwindWebApp.Pages.Territories
{
    public class QueryModel : PageModel
    {
        private readonly RegionServices _regionServices;
        private readonly TerritoryServices _territoryServices;

        public QueryModel(RegionServices regionServices, TerritoryServices territoryServices)
        {
            _regionServices = regionServices;
            _territoryServices = territoryServices;

            Regions = _regionServices.GetAll();
        }

        public List<Region> Regions { get; private set; }

        [BindProperty]
        public int? SelectedRegionId { get; set; }

        public List<Territory> QueryResultList { get; private set; }
        
        public string? FeedbackMessage { get; set; }

        [BindProperty]
        public string TerritoryQuery { get; set; }

        public void OnGet()
        {
        }

        public void OnPostFilterByTerritory()
        {
            if (TerritoryQuery != null)
            {
                QueryResultList = _territoryServices.FindByPartialName(TerritoryQuery);
            }
            else
            {
                FeedbackMessage = "You need to enter a territory first.";
            }
        }

        public void OnPostFilterByRegion()
        {
            // Check if a valid region was selected
            if (SelectedRegionId.HasValue)
            {
                QueryResultList = _territoryServices.FindByRegionId(SelectedRegionId.Value);
            }
            else
            {
                FeedbackMessage = "You must select a region first.";
            }
        }
    }
}

WestwindSolution/WestwindWebApp/Pages/Products/ProductCategory.cshtml
@page
@model WestwindWebApp.Pages.Products.ProductCategoryModel
@{
}
<h1>Product Category</h1>

@if (Model.InfoMessage != null)
{
    <div class="alert alert-info">
        @Model.InfoMessage
    </div>
}
@if (Model.ErrorMessage != null)
{
    <div class="alert alert-danger">
        @Model.ErrorMessage
    </div>
}

<form method="post">
    <div>
        <label asp-for="SelectedCategoryId">Select Category</label>
        <select asp-for="SelectedCategoryId"
                asp-items="Model.CategorySelectList"
                class="form-select form-select-lg mb-3"
                aria-label=".form-select-lg category">
            <option>---select a category---</option>
        </select>
    </div>
    <div>
        <button type="submit" 
            asp-page-handler="FetchProducts"
            class="btn btn-primary">
            Fetch Products
        </button>
        <button type="submit"
                asp-page-handler="Clear"
                class="btn btn-secondary">
            Clear
        </button>
        <button type="submit"
                asp-page-handler="NewProduct"
                class="btn btn-success">
            New Product
        </button>
    </div>

    @if (Model.QueryProductResultList != null && Model.QueryProductResultList.Count > 0)
    {
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Product Name</th>
                    <th>Supplier</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var currentProduct in Model.QueryProductResultList)
                {
                    <tr>
                        <td>@currentProduct.Id</td>
                        <td>@currentProduct.ProductName</td>
                        <td>
                            <select>
                                @* If the SupplierId is nullable then we can set as selected as shown below:
                                    <option selected=@(currentProduct.SupplierId == null)>No Supplier</option>
                                *@

                                @foreach(var item in Model.SupplierSelectList)
                                {
                                    @*if (int.Parse(item.Value) == currentProduct.SupplierId) 
                                    {
                                        <option value="@item.Value" selected>@item.Text</option>
                                    }
                                    else
                                    {
                                        <option value="@item.Value">@item.Text</option>
                                    }*@
                                    @*
                                        Instead of using an if statement to output a conditional HTML attribute
                                        you can a razor inline expression to determine if the HTML attribute is included
                        such as the selected attribute is only included if the @(boolean_expression) evaluates to true
                                            selected = @(boolean_expression)
                                    *@
                                    <option value="@item.Value"
                                            selected=@(int.Parse(item.Value) == currentProduct.SupplierId)>
                                            @item.Text
                                    </option>
                                }
                            </select>
                        </td>
                        <td><a href="/Products/ProductCrud/@currentProduct.Id">edit</a></td>
                    </tr>
                }
            </tbody>
        </table>
    }
</form>

WestwindSolution/WestwindWebApp/Pages/Products/ProductCrud.cshtml
@page "{EditProductId?}"
@model WestwindWebApp.Pages.Products.ProductCrudModel
@{
}
<h1>Product Maintenance</h1>

@if (Model.EditProductId.HasValue) 
{
    <h2>Edit/Delete Product</h2>
}
else
{
    <h2>Create New Product</h2>
}

@if (Model.InfoMessage != null)
{
    <div class="alert alert-info">
        @Model.InfoMessage
    </div>
}
@if (Model.ErrorMessage != null)
{
    <div class="alert alert-danger">
        @Model.ErrorMessage
    </div>
}

<form method="post">
    <div>
        <label asp-for="CurrentProduct.ProductName">Product Name</label>
        <input asp-for="CurrentProduct.ProductName" class="form-control"/>
    </div>
    <div>
        <label asp-for="CurrentProduct.UnitPrice">Unit Price</label>
        <input asp-for="CurrentProduct.UnitPrice" class="form-control" />
    </div>
</form>

WestwindSolution/WestwindWebApp/Pages/Products/Query.cshtml
@page 
@model WestwindWebApp.Pages.Products.QueryModel
@{
}

@if (!string.IsNullOrWhiteSpace(Model.FeedbackMessage)) 
{
    <div class="alert alert-info">
        @Model.FeedbackMessage
    </div>
}

<form method="post">
    <div class="mb-3">

        <label asp-for="SelectedCategoryId">Category</label>
       @* <select asp-for="SelectedCategoryId"
                class="form-select" 
                aria-label="Category">
            <option selected >--- select a category ---</option>            
            @foreach(var currentCategory in Model.CategoryList) 
            {
                <option value="@currentCategory.Id">@currentCategory.CategoryName</option>
            }
        </select>*@
        <select 
            asp-for="SelectedCategoryId"
            asp-items="Model.CategorySelectionList">
            <option selected>--- select a category ---</option>
        </select>
    </div>

    <div class="mb-3">
        <label asp-for="QueryProductName" lass="form-label">Product Name</label>
        <input class="form-control"
               asp-for="QueryProductName" />
    </div>

    <button type="submit" asp-page-handler="SearchByCategory" class="btn btn-primary">Search by Category</button>
    <button type="submit" asp-page-handler="SearchByProductName" class="btn btn-primary">Search by Product Name</button>
    <button type="submit" asp-page-handler="ClearForm" class="btn btn-light">Clear</button>

</form>

@if (Model.QueryResultList != null)
{
    <table class="table" style="color:yellowgreen; font-family: Verdana; ">
        <thead>
            <tr>
                <th>ID</th>
                <th>Product Name</th>
                <th>Unit Price</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var currentProduct in Model.QueryResultList)
            {
                <tr>
                    <td>@currentProduct.Id</td>
                    <td>@currentProduct.ProductName</td>
                    <td>@currentProduct.UnitPrice</td>
                </tr>
            }
        </tbody>
    </table>
}